In [4]:
from google.colab import files

uploaded = files.upload()

Saving inventory DA.csv to inventory DA (1).csv
Saving order_items DA.csv to order_items DA (1).csv
Saving orders DA.csv to orders DA (1).csv
Saving payments DA.csv to payments DA (1).csv
Saving products DA.csv to products DA (1).csv
Saving returns DA.csv to returns DA (1).csv
Saving suppliers DA.csv to suppliers DA (1).csv
Saving customers DA.csv to customers DA (1).csv

Load all files

In [5]:
import pandas as pd

customers = pd.read_csv("customers DA.csv")
orders = pd.read_csv("orders DA.csv")
order_items = pd.read_csv("order_items DA.csv")
payments = pd.read_csv("payments DA.csv")
products = pd.read_csv("products DA.csv")
returns = pd.read_csv("returns DA.csv")
suppliers = pd.read_csv("suppliers DA.csv")
inventory = pd.read_csv("inventory DA.csv")

In [6]:
print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Payments:", payments.shape)
print("Products:", products.shape)
print("Returns:", returns.shape)
print("Suppliers:", suppliers.shape)
print("Inventory:", inventory.shape)

Customers: (10000, 17)
Orders: (50000, 19)
Order Items: (100000, 11)
Payments: (50000, 13)
Products: (1000, 17)
Returns: (10000, 10)
Suppliers: (200, 14)
Inventory: (1000, 11)

import library

In [7]:
import pandas as pd

In [8]:
import os

os.listdir()

['.config',
 'orders DA.csv',
 'payments DA (1).csv',
 'orders DA (1).csv',
 'products DA (1).csv',
 'order_items DA (1).csv',
 'customers DA.csv',
 'returns DA.csv',
 'payments DA.csv',
 'order_items DA.csv',
 'suppliers DA.csv',
 'products DA.csv',
 'inventory DA.csv',
 'customers DA (1).csv',
 'suppliers DA (1).csv',
 'returns DA (1).csv',
 'inventory DA (1).csv',
 'sample_data']

Customers Data cleaning

In [9]:
customers.head()

,customer_id,first_name,last_name,email,phone,city,state,pincode,gender,age,segment,registration_date,last_login_date,is_verified,is_active,total_orders,total_spent
0,CUST00001,Kunal,Gupta,kunal.gupta223@gmail.com,9117912889,Guwahati,Assam,314040,Male,54,New,30-07-2024,10-04-2025,0,1,7,1028341.51
1,CUST00002,Aryan,Gupta,aryan.gupta336@yahoo.in,9271550550,Navi Mumbai,Maharashtra,799535,Female,26,Budget,05-07-2023,03-05-2024,1,1,1,20337.39
2,CUST00003,Akash,Chatterjee,akash.chatterjee584@hotmail.com,9559676548,Surat,Gujarat,738196,Female,24,Regular,14-05-2022,31-10-2023,1,1,7,265688.26
3,CUST00004,Madhuri,Walia,madhuri.walia878@gmail.com,9673322422,Gwalior,Madhya Pradesh,238106,Female,23,Regular,21-01-2025,22-05-2025,1,0,7,173446.94
4,CUST00005,Vishal,Das,vishal.das342@yahoo.in,9920855521,Dhanbad,Jharkhand,783291,Female,59,Regular,06-06-2023,29-03-2024,1,0,4,239808.60

In [10]:
customers.shape

(10000, 17)

In [11]:
customers.columns

Index(['customer_id', 'first_name', 'last_name', 'email', 'phone', 'city',
       'state', 'pincode', 'gender', 'age', 'segment', 'registration_date',
       'last_login_date', 'is_verified', 'is_active', 'total_orders',
       'total_spent'],
      dtype='object')

In [12]:
customers.dtypes

customer_id           object
first_name            object
last_name             object
email                 object
phone                  int64
city                  object
state                 object
pincode                int64
gender                object
age                    int64
segment               object
registration_date     object
last_login_date       object
is_verified            int64
is_active              int64
total_orders           int64
total_spent          float64
dtype: object

In [13]:
customers.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                0
phone                0
city                 0
state                0
pincode              0
gender               0
age                  0
segment              0
registration_date    0
last_login_date      0
is_verified          0
is_active            0
total_orders         0
total_spent          0
dtype: int64

In [14]:
customers.isnull().mean().mul(100).round(2)

customer_id          0.0
first_name           0.0
last_name            0.0
email                0.0
phone                0.0
city                 0.0
state                0.0
pincode              0.0
gender               0.0
age                  0.0
segment              0.0
registration_date    0.0
last_login_date      0.0
is_verified          0.0
is_active            0.0
total_orders         0.0
total_spent          0.0
dtype: float64

In [15]:
customers.duplicated().sum()

np.int64(0)

In [16]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [17]:
(customers["total_orders"] == 0).sum()

np.int64(457)

In [18]:
customers["is_verified"].value_counts()

is_verified
1    8418
0    1582
Name: count, dtype: int64

In [19]:
customers["is_active"].value_counts()

is_active
1    8755
0    1245
Name: count, dtype: int64

In [20]:
customers["age"].describe()

count    10000.00000
mean        41.67630
std         13.83438
min         18.00000
25%         30.00000
50%         42.00000
75%         54.00000
max         65.00000
Name: age, dtype: float64

In [21]:
customers["total_orders"].describe()

count    10000.000000
mean         5.000000
std          3.069942
min          0.000000
25%          3.000000
50%          5.000000
75%          7.000000
max         19.000000
Name: total_orders, dtype: float64

In [22]:
customers["total_spent"].describe()

count    1.000000e+04
mean     3.147386e+05
std      2.903266e+05
min      0.000000e+00
25%      8.842337e+04
50%      2.356611e+05
75%      4.660584e+05
max      1.999913e+06
Name: total_spent, dtype: float64

In [23]:
customers["gender"].value_counts(dropna=False)

gender
Male      5168
Female    4564
Other      268
Name: count, dtype: int64

In [24]:
customers["segment"].value_counts(dropna=False)

segment
Regular     4026
Budget      2505
Premium     1501
New         1488
Inactive     480
Name: count, dtype: int64

In [25]:
customers["registration_date"].head(10)

0    30-07-2024
1    05-07-2023
2    14-05-2022
3    21-01-2025
4    06-06-2023
5    06-04-2022
6    10-06-2022
7    04-08-2021
8    24-11-2022
9    20-11-2024
Name: registration_date, dtype: object

Convert registration_date to datetime

In [26]:
customers["registration_date"] = pd.to_datetime(
    customers["registration_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [27]:
customers["registration_date"].dtype

dtype('<M8[ns]')

In [28]:
customers["registration_date"].isnull().sum()

np.int64(0)

In [29]:
customers["last_login_date"].head(10)

0    10-04-2025
1    03-05-2024
2    31-10-2023
3    22-05-2025
4    29-03-2024
5    21-10-2022
6    06-04-2023
7    29-03-2023
8    18-05-2025
9    21-01-2025
Name: last_login_date, dtype: object

Convert last_login_date to datetime

In [30]:
customers["last_login_date"] = pd.to_datetime(
    customers["last_login_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [31]:
customers["last_login_date"].dtype

dtype('<M8[ns]')

In [32]:
customers["last_login_date"].isnull().sum()

np.int64(0)

In [33]:
customers["phone"].head(10)

0    9117912889
1    9271550550
2    9559676548
3    9673322422
4    9920855521
5    9809180864
6    9718044438
7    9143287667
8    9238159208
9    9938859478
Name: phone, dtype: int64

In [34]:
customers["phone"].astype(str).str.len().value_counts()

phone
10    10000
Name: count, dtype: int64

In [35]:
customers["pincode"].astype(str).str.len().value_counts()

pincode
6    10000
Name: count, dtype: int64

In [36]:
email_pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"

customers["email"].str.match(email_pattern).value_counts()

email
True    10000
Name: count, dtype: int64

Validate total_spent

In [37]:
customers["total_spent"].lt(0).sum()

np.int64(0)

In [38]:
customers["total_spent"].nlargest(10)

3450    1999913.04
5551    1997346.16
6800    1983951.26
7345    1928170.04
5534    1918090.04
26      1893655.96
7424    1892535.76
7573    1863718.85
1061    1858684.83
4362    1857479.68
Name: total_spent, dtype: float64

In [39]:
customers[
    (customers["total_orders"] == 0) &
    (customers["total_spent"] > 0)
].shape

(0, 17)

In [40]:
customers[
    (customers["total_orders"] > 0) &
    (customers["total_spent"] == 0)
].shape

(0, 17)

In [41]:
customers.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                0
phone                0
city                 0
state                0
pincode              0
gender               0
age                  0
segment              0
registration_date    0
last_login_date      0
is_verified          0
is_active            0
total_orders         0
total_spent          0
dtype: int64

In [42]:
customers.to_csv("customers_cleaned.csv", index=False)

In [43]:
import os

os.path.exists("customers_cleaned.csv")

True

Products data cleaning

In [44]:
products.shape

(1000, 17)

In [45]:
products.dtypes

product_id        object
product_name      object
category          object
subcategory       object
brand             object
sku               object
mrp                int64
selling_price      int64
cost_price         int64
gst_rate           int64
hsn_code           int64
weight_grams       int64
supplier_id       object
rating           float64
review_count       int64
is_active          int64
launch_date       object
dtype: object

In [46]:
products.isnull().sum()

product_id       0
product_name     0
category         0
subcategory      0
brand            0
sku              0
mrp              0
selling_price    0
cost_price       0
gst_rate         0
hsn_code         0
weight_grams     0
supplier_id      0
rating           0
review_count     0
is_active        0
launch_date      0
dtype: int64

In [47]:
products.duplicated().sum()

np.int64(0)

In [48]:
products["product_id"].duplicated().sum()

np.int64(0)

In [49]:
products[
    (products["selling_price"] > products["mrp"]) |
    (products["cost_price"] > products["selling_price"])
].shape

(0, 17)

In [50]:
products["gst_rate"].value_counts().sort_index()

gst_rate
0     200
5     100
12    300
18    300
28    100
Name: count, dtype: int64

In [51]:
products["rating"].describe()

count    1000.000000
mean        4.040300
std         0.499736
min         3.200000
25%         3.600000
50%         4.000000
75%         4.500000
max         4.900000
Name: rating, dtype: float64

In [52]:
products["review_count"].lt(0).sum()

np.int64(0)

In [53]:
(products["weight_grams"] <= 0).sum()

np.int64(0)

In [54]:
(products["selling_price"] <= 0).sum(), (products["cost_price"] <= 0).sum()

(np.int64(0), np.int64(0))

In [55]:
products["is_active"].value_counts()

is_active
1    921
0     79
Name: count, dtype: int64

In [56]:
products["launch_date"].head(10)

0    29-01-2025
1    17-05-2024
2    28-12-2024
3    04-05-2023
4    27-11-2023
5    28-04-2025
6    02-09-2023
7    28-06-2024
8    23-11-2022
9    02-05-2023
Name: launch_date, dtype: object

In [57]:
products["launch_date"].astype(str).str.len().value_counts()

launch_date
10    1000
Name: count, dtype: int64

convert launch_date to dtaetime

In [58]:
products["launch_date"] = pd.to_datetime(
    products["launch_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [59]:
products["launch_date"].dtype

dtype('<M8[ns]')

In [60]:
products["launch_date"].isnull().sum()

np.int64(0)

In [61]:
products["sku"].duplicated().sum()

np.int64(0)

In [62]:
products["supplier_id"].value_counts(dropna=False).tail()

supplier_id
SUP0193    1
SUP0170    1
SUP0101    1
SUP0073    1
SUP0107    1
Name: count, dtype: int64

In [63]:
products["supplier_id"].str.match(r"^SUP\d{4}$").value_counts()

supplier_id
True    1000
Name: count, dtype: int64

In [64]:
products["hsn_code"].astype(str).str.len().value_counts()

hsn_code
4    1000
Name: count, dtype: int64

In [65]:
products["product_name"].str.strip().eq("").sum()

np.int64(0)

In [66]:
products["category"].str.strip().eq("").sum()

np.int64(0)

In [67]:
products["subcategory"].str.strip().eq("").sum()

np.int64(0)

In [68]:
products["brand"].str.strip().eq("").sum()

np.int64(0)

In [69]:
products["product_id"].str.match(r"^PROD\d{4}$").value_counts()

product_id
False    1000
Name: count, dtype: int64

In [70]:
products["product_id"].head(10)

0    PRD0001
1    PRD0002
2    PRD0003
3    PRD0004
4    PRD0005
5    PRD0006
6    PRD0007
7    PRD0008
8    PRD0009
9    PRD0010
Name: product_id, dtype: object

In [71]:
products["product_id"].str.match(r"^PRD\d{4}$").value_counts()

product_id
True    1000
Name: count, dtype: int64

In [72]:
products.isnull().sum()

product_id       0
product_name     0
category         0
subcategory      0
brand            0
sku              0
mrp              0
selling_price    0
cost_price       0
gst_rate         0
hsn_code         0
weight_grams     0
supplier_id      0
rating           0
review_count     0
is_active        0
launch_date      0
dtype: int64

In [73]:
products.to_csv("products_cleaned.csv", index=False)

In [75]:
import os

os.path.exists("products_cleaned.csv")

True

Payments data cleaning

In [76]:
payments = pd.read_csv("payments DA.csv")

In [77]:
payments.shape

(50000, 13)

In [78]:
payments.dtypes

payment_id         object
order_id           object
customer_id        object
payment_date       object
payment_time       object
payment_method     object
amount            float64
status             object
transaction_id     object
bank_name          object
gateway            object
refund_amount       int64
refund_date       float64
dtype: object

In [79]:
payments.columns

Index(['payment_id', 'order_id', 'customer_id', 'payment_date', 'payment_time',
       'payment_method', 'amount', 'status', 'transaction_id', 'bank_name',
       'gateway', 'refund_amount', 'refund_date'],
      dtype='object')

In [80]:
payments.isnull().sum()

payment_id            0
order_id              0
customer_id           0
payment_date          0
payment_time          0
payment_method        0
amount                0
status                0
transaction_id        0
bank_name             0
gateway               0
refund_amount         0
refund_date       50000
dtype: int64

In [81]:
payments["refund_amount"].value_counts(dropna=False)

refund_amount
0    50000
Name: count, dtype: int64

In [82]:
payments.duplicated().sum()

np.int64(0)

In [83]:
payments["payment_id"].duplicated().sum()

np.int64(0)

In [84]:
payments["amount"].describe()

count    5.000000e+04
mean     6.294771e+04
std      9.789750e+04
min      1.360700e+02
25%      6.893520e+03
50%      2.418338e+04
75%      7.149574e+04
max      1.133382e+06
Name: amount, dtype: float64

In [85]:
payments[payments["amount"] < 0].shape

(0, 13)

In [86]:
payments["status"].value_counts()

status
Success    48252
Failed      1748
Name: count, dtype: int64

In [87]:
failure_rate = (payments["status"].eq("Failed").sum() / len(payments)) * 100
failure_rate

np.float64(3.496)

In [88]:
payments["payment_method"].value_counts()

payment_method
UPI                 17570
Credit Card         10007
Debit Card           7624
Cash on Delivery     5883
Net Banking          4026
EMI                  2943
Wallet               1947
Name: count, dtype: int64

In [89]:
payments["transaction_id"].duplicated().sum()

np.int64(0)

In [90]:
payments["payment_date"].head()

0    22-05-2025
1    16-10-2023
2    08-10-2023
3    02-10-2023
4    15-06-2024
Name: payment_date, dtype: object

convert payment-date to datetime

In [91]:
payments["payment_date"] = pd.to_datetime(
    payments["payment_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [92]:
payments["payment_date"].dtype

dtype('<M8[ns]')

In [93]:
payments["payment_date"].isnull().sum()

np.int64(0)

In [94]:
payments["payment_time"].head()

0    17:10:00
1    05:32:00
2    12:32:00
3    08:05:00
4    20:19:00
Name: payment_time, dtype: object

convert payment_time to proper time format

In [95]:
payments["payment_time"] = pd.to_datetime(
    payments["payment_time"],
    format="%H:%M:%S",
    errors="coerce"
).dt.time

In [96]:
payments["payment_time"].head()

0    17:10:00
1    05:32:00
2    12:32:00
3    08:05:00
4    20:19:00
Name: payment_time, dtype: object

In [97]:
payments["payment_time"].isnull().sum()

np.int64(0)

In [98]:
payments["refund_amount"].dtype

dtype('int64')

In [99]:
payments["refund_date"].dtype

dtype('float64')

In [100]:
payments[[
    "payment_id",
    "order_id",
    "customer_id",
    "transaction_id",
    "bank_name",
    "gateway"
]].dtypes

payment_id        object
order_id          object
customer_id       object
transaction_id    object
bank_name         object
gateway           object
dtype: object

In [101]:
payments["payment_id"].head(10)

0    PAY000001
1    PAY000002
2    PAY000003
3    PAY000004
4    PAY000005
5    PAY000006
6    PAY000007
7    PAY000008
8    PAY000009
9    PAY000010
Name: payment_id, dtype: object

In [102]:
payments["payment_id"].str.match(r"^PAY\d{6}$").value_counts()

payment_id
True    50000
Name: count, dtype: int64

In [103]:
payments["order_id"].head(10)

0    ORD000001
1    ORD000002
2    ORD000003
3    ORD000004
4    ORD000005
5    ORD000006
6    ORD000007
7    ORD000008
8    ORD000009
9    ORD000010
Name: order_id, dtype: object

In [104]:
payments["order_id"].str.match(r"^ORD\d{6}$").value_counts()

order_id
True    50000
Name: count, dtype: int64

In [105]:
payments["customer_id"].head(10)

0    CUST02946
1    CUST04232
2    CUST08078
3    CUST09612
4    CUST03065
5    CUST00643
6    CUST00754
7    CUST02760
8    CUST01691
9    CUST03540
Name: customer_id, dtype: object

In [106]:
payments["customer_id"].str.match(r"^CUST\d{5}$").value_counts()

customer_id
True    50000
Name: count, dtype: int64

In [107]:
payments["transaction_id"].head(10)

0    TXN5110698474
1    TXN4067460377
2    TXN7056710694
3    TXN7460208257
4    TXN5835043807
5    TXN6831058137
6    TXN3252120864
7    TXN5359581303
8    TXN1794912055
9    TXN9731645004
Name: transaction_id, dtype: object

In [108]:
payments["transaction_id"].str.match(r"^TXN\d{10}$").value_counts()

transaction_id
True    50000
Name: count, dtype: int64

In [109]:
payments["bank_name"].value_counts()

bank_name
HDFC Bank         5054
IndusInd          5044
Bank of Baroda    5039
Canara Bank       5026
SBI               5019
Kotak Mahindra    5004
ICICI Bank        4972
Axis Bank         4970
Yes Bank          4955
PNB               4917
Name: count, dtype: int64

In [110]:
payments["gateway"].value_counts()

gateway
BillDesk      7222
Google Pay    7182
PhonePe       7170
Razorpay      7126
PayU          7121
CCAvenue      7118
Paytm         7061
Name: count, dtype: int64

In [111]:
payments[
    (payments["refund_amount"] == 0) &
    (payments["refund_date"].notna())
].shape

(0, 13)

In [112]:
payments[payments["amount"] <= 0].shape

(0, 13)

In [113]:
payments.dtypes

payment_id                object
order_id                  object
customer_id               object
payment_date      datetime64[ns]
payment_time              object
payment_method            object
amount                   float64
status                    object
transaction_id            object
bank_name                 object
gateway                   object
refund_amount              int64
refund_date              float64
dtype: object

In [114]:
payments.isnull().sum()

payment_id            0
order_id              0
customer_id           0
payment_date          0
payment_time          0
payment_method        0
amount                0
status                0
transaction_id        0
bank_name             0
gateway               0
refund_amount         0
refund_date       50000
dtype: int64

In [115]:
payments.to_csv("payments_cleaned.csv", index=False)

In [116]:
import os

os.path.exists("payments_cleaned.csv")

True

order items data
cleaning

In [117]:
order_items = pd.read_csv("order_items DA.csv")

In [118]:
order_items.shape

(100000, 11)

In [119]:
order_items.columns

Index(['item_id', 'order_id', 'product_id', 'product_name', 'category',
       'quantity', 'unit_price', 'gst_rate', 'gst_amount', 'discount_amount',
       'total_price'],
      dtype='object')

In [120]:
order_items.isnull().sum()

item_id            0
order_id           0
product_id         0
product_name       0
category           0
quantity           0
unit_price         0
gst_rate           0
gst_amount         0
discount_amount    0
total_price        0
dtype: int64

In [121]:
order_items.duplicated().sum()

np.int64(0)

In [122]:
order_items["item_id"].duplicated().sum()

np.int64(0)

In [123]:
order_items["item_id"].head(10)

0    ITM0000001
1    ITM0000002
2    ITM0000003
3    ITM0000004
4    ITM0000005
5    ITM0000006
6    ITM0000007
7    ITM0000008
8    ITM0000009
9    ITM0000010
Name: item_id, dtype: object

In [124]:
order_items["item_id"].str.match(r"^ITM\d{7}$").value_counts()

item_id
True    100000
Name: count, dtype: int64

In [125]:
order_items["order_id"].str.match(r"^ORD\d{6}$").value_counts()

order_id
True    100000
Name: count, dtype: int64

In [126]:
order_items["product_id"].head(10)

0    PRD0522
1    PRD0094
2    PRD0613
3    PRD0556
4    PRD0026
5    PRD0518
6    PRD0286
7    PRD0291
8    PRD0022
9    PRD0750
Name: product_id, dtype: object

In [127]:
order_items["product_id"].str.match(r"^PRD\d{4}$").value_counts()

product_id
True    100000
Name: count, dtype: int64

In [128]:
order_items["quantity"].describe()

count    100000.000000
mean          2.002070
std           0.815986
min           1.000000
25%           1.000000
50%           2.000000
75%           3.000000
max           3.000000
Name: quantity, dtype: float64

In [129]:
(order_items["quantity"] % 1 != 0).sum()

np.int64(0)

Convert quantity to integer

In [130]:
order_items["quantity"] = order_items["quantity"].astype(int)

In [131]:
order_items["quantity"].dtype

dtype('int64')

In [132]:
order_items["unit_price"].describe()

count    100000.000000
mean      13456.451340
std       26067.401044
min         108.000000
25%        1263.000000
50%        3579.000000
75%       11526.000000
max      149361.000000
Name: unit_price, dtype: float64

In [133]:
order_items[order_items["unit_price"] <= 0].shape

(0, 11)

In [134]:
order_items["gst_rate"].value_counts()

gst_rate
18    30036
12    30001
0     19975
5     10002
28     9986
Name: count, dtype: int64

In [135]:
order_items[order_items["gst_amount"] < 0].shape

(0, 11)

In [136]:
order_items[order_items["discount_amount"] < 0].shape

(0, 11)

In [137]:
order_items[order_items["total_price"] <= 0].shape

(0, 11)

In [138]:
order_items[[
    "quantity",
    "unit_price",
    "gst_rate",
    "gst_amount",
    "discount_amount",
    "total_price"
]].head(10)

   quantity  unit_price  gst_rate  gst_amount  discount_amount  total_price
0         1       40989        12     4918.68          7861.45     38046.23
1         1       62532        18    11255.76         12373.11     61414.65
2         1        1585        12      190.20           251.89      1523.31
3         3        1107        12      398.52           631.44      3088.08
4         2      114448        18    41201.28         18707.35    251389.93
5         1       16599        12     1991.88           173.22     18417.66
6         3        4364        12     1571.04           523.64     14139.40
7         2       12887        12     3092.88          4029.94     24836.94
8         2       69701        18    25092.36          7805.07    156689.29
9         3         594         0        0.00           225.20      1556.80

In [139]:
expected_total = (
    order_items["quantity"] * order_items["unit_price"]
    + order_items["gst_amount"]
    - order_items["discount_amount"]
)

(order_items["total_price"].round(2) != expected_total.round(2)).sum()

np.int64(0)

In [140]:
order_items[["product_name", "category"]].apply(
    lambda x: x.astype(str).str.strip().eq("").sum()
)

product_name    0
category        0
dtype: int64

In [141]:
order_items.dtypes

item_id             object
order_id            object
product_id          object
product_name        object
category            object
quantity             int64
unit_price           int64
gst_rate             int64
gst_amount         float64
discount_amount    float64
total_price        float64
dtype: object

In [142]:
order_items.isnull().sum()

item_id            0
order_id           0
product_id         0
product_name       0
category           0
quantity           0
unit_price         0
gst_rate           0
gst_amount         0
discount_amount    0
total_price        0
dtype: int64

In [143]:
order_items.to_csv("order_items_cleaned.csv", index=False)

In [144]:
import os

os.path.exists("order_items_cleaned.csv")

True

Orders data cleaning

In [145]:
orders.shape

(50000, 19)

In [146]:
# ============================================================
# E-COMMERCE DATA ANALYTICS PROJECT
# CLEANING: ORDERS, RETURNS, SUPPLIERS & INVENTORY
# ============================================================

import pandas as pd
import numpy as np
import os

# ------------------------------------------------------------
# 1. LOAD REMAINING DATASETS
# ------------------------------------------------------------

orders = pd.read_csv("orders DA.csv")
returns = pd.read_csv("returns DA.csv")
suppliers = pd.read_csv("suppliers DA.csv")
inventory = pd.read_csv("inventory DA.csv")

print("Datasets loaded successfully.")
print("Orders:", orders.shape)
print("Returns:", returns.shape)
print("Suppliers:", suppliers.shape)
print("Inventory:", inventory.shape)


# ============================================================
# 2. ORDERS CLEANING
# ============================================================

print("\n========== ORDERS CLEANING ==========")

# Basic structure
print("\nShape:")
print(orders.shape)

print("\nMissing values:")
print(orders.isnull().sum())

print("\nDuplicate rows:")
print(orders.duplicated().sum())


# Remove completely duplicated rows only
orders = orders.drop_duplicates().copy()


# ------------------------------------------------------------
# ID VALIDATION
# ------------------------------------------------------------

print("\nDuplicate order_id:")
print(orders["order_id"].duplicated().sum())

# Check order ID format
invalid_order_id = ~orders["order_id"].astype(str).str.match(
    r"^ORD\d{6}$",
    na=False
)

print("\nInvalid order_id:")
print(invalid_order_id.sum())


# ------------------------------------------------------------
# DATE CLEANING
# ------------------------------------------------------------

date_columns = [
    "order_date",
    "delivered_date"
]

for col in date_columns:
    if col in orders.columns:
        orders[col] = pd.to_datetime(
            orders[col],
            format="%d-%m-%Y",
            errors="coerce"
        )

print("\nDate columns converted.")


# ------------------------------------------------------------
# NUMERIC COLUMN CLEANING
# ------------------------------------------------------------

numeric_columns = [
    "quantity",
    "unit_price",
    "gst_rate",
    "gst_amount",
    "discount_amount",
    "total_amount",
    "final_amount"
]

for col in numeric_columns:
    if col in orders.columns:
        orders[col] = pd.to_numeric(
            orders[col],
            errors="coerce"
        )


# ------------------------------------------------------------
# QUANTITY CHECK
# ------------------------------------------------------------

if "quantity" in orders.columns:

    print("\nInvalid quantity:")
    print((orders["quantity"] <= 0).sum())

    # Convert whole-number quantities to integer
    if orders["quantity"].notna().all():
        orders["quantity"] = orders["quantity"].astype(int)


# ------------------------------------------------------------
# PRICE / AMOUNT CHECKS
# ------------------------------------------------------------

for col in [
    "unit_price",
    "gst_amount",
    "discount_amount",
    "total_amount",
    "final_amount"
]:

    if col in orders.columns:

        print(f"\nNegative values in {col}:")
        print((orders[col] < 0).sum())


# ------------------------------------------------------------
# ORDER STATUS CHECK
# ------------------------------------------------------------

if "order_status" in orders.columns:

    print("\nOrder status:")
    print(orders["order_status"].value_counts(dropna=False))


# ------------------------------------------------------------
# DELIVERY DATE LOGIC
# delivered_date should not be before order_date
# ------------------------------------------------------------

if "order_date" in orders.columns and "delivered_date" in orders.columns:

    invalid_delivery_dates = (
        orders["delivered_date"].notna()
        & orders["order_date"].notna()
        & (orders["delivered_date"] < orders["order_date"])
    )

    print("\nDelivered date before order date:")
    print(invalid_delivery_dates.sum())


# ------------------------------------------------------------
# FINAL AMOUNT OUTLIER CHECK
# ------------------------------------------------------------

if "final_amount" in orders.columns:

    print("\nOrders above ₹5,00,000:")
    print((orders["final_amount"] > 500000).sum())


# ------------------------------------------------------------
# ORDERS FINAL VALIDATION
# ------------------------------------------------------------

print("\nFinal Orders missing values:")
print(orders.isnull().sum())

print("\nFinal Orders duplicates:")
print(orders.duplicated().sum())


# SAVE ORDERS
orders.to_csv("orders_cleaned.csv", index=False)

print("\nOrders cleaned and saved successfully.")


# ============================================================
# 3. RETURNS CLEANING
# ============================================================

print("\n========== RETURNS CLEANING ==========")

print("\nShape:")
print(returns.shape)

print("\nMissing values:")
print(returns.isnull().sum())

print("\nDuplicate rows:")
print(returns.duplicated().sum())

# Remove only completely duplicated rows
returns = returns.drop_duplicates().copy()


# ------------------------------------------------------------
# ID CHECKS
# ------------------------------------------------------------

if "return_id" in returns.columns:

    print("\nDuplicate return_id:")
    print(returns["return_id"].duplicated().sum())

    invalid_return_id = ~returns["return_id"].astype(str).str.match(
        r"^RET\d{6}$",
        na=False
    )

    print("\nInvalid return_id:")
    print(invalid_return_id.sum())


if "order_id" in returns.columns:

    invalid_return_order_id = ~returns["order_id"].astype(str).str.match(
        r"^ORD\d{6}$",
        na=False
    )

    print("\nInvalid return order_id:")
    print(invalid_return_order_id.sum())


# ------------------------------------------------------------
# DATE COLUMNS
# ------------------------------------------------------------

return_date_columns = [
    "return_date"
]

for col in return_date_columns:
    if col in returns.columns:
        returns[col] = pd.to_datetime(
            returns[col],
            format="%d-%m-%Y",
            errors="coerce"
        )


# ------------------------------------------------------------
# NUMERIC COLUMNS
# ------------------------------------------------------------

return_numeric_columns = [
    "refund_amount",
    "return_amount"
]

for col in return_numeric_columns:
    if col in returns.columns:
        returns[col] = pd.to_numeric(
            returns[col],
            errors="coerce"
        )

        print(f"\nNegative values in {col}:")
        print((returns[col] < 0).sum())


# ------------------------------------------------------------
# RETURN STATUS / REASON
# ------------------------------------------------------------

for col in ["return_status", "return_reason"]:

    if col in returns.columns:

        print(f"\n{col}:")
        print(returns[col].value_counts(dropna=False))


# ------------------------------------------------------------
# FINAL RETURNS VALIDATION
# ------------------------------------------------------------

print("\nFinal Returns missing values:")
print(returns.isnull().sum())

print("\nFinal Returns duplicates:")
print(returns.duplicated().sum())


# SAVE RETURNS
returns.to_csv("returns_cleaned.csv", index=False)

print("\nReturns cleaned and saved successfully.")


# ============================================================
# 4. SUPPLIERS CLEANING
# ============================================================

print("\n========== SUPPLIERS CLEANING ==========")

print("\nShape:")
print(suppliers.shape)

print("\nMissing values:")
print(suppliers.isnull().sum())

print("\nDuplicate rows:")
print(suppliers.duplicated().sum())

suppliers = suppliers.drop_duplicates().copy()


# ------------------------------------------------------------
# SUPPLIER ID
# ------------------------------------------------------------

if "supplier_id" in suppliers.columns:

    print("\nDuplicate supplier_id:")
    print(suppliers["supplier_id"].duplicated().sum())

    invalid_supplier_id = ~suppliers["supplier_id"].astype(str).str.match(
        r"^SUP\d{4}$",
        na=False
    )

    print("\nInvalid supplier_id:")
    print(invalid_supplier_id.sum())


# ------------------------------------------------------------
# NUMERIC COLUMNS
# ------------------------------------------------------------

supplier_numeric_columns = [
    "rating",
    "total_products",
    "total_orders"
]

for col in supplier_numeric_columns:

    if col in suppliers.columns:

        suppliers[col] = pd.to_numeric(
            suppliers[col],
            errors="coerce"
        )

        print(f"\nNegative values in {col}:")
        print((suppliers[col] < 0).sum())


# ------------------------------------------------------------
# EMAIL CHECK
# ------------------------------------------------------------

if "email" in suppliers.columns:

    invalid_email = ~suppliers["email"].astype(str).str.match(
        r"^[^@\s]+@[^@\s]+\.[^@\s]+$",
        na=False
    )

    print("\nInvalid supplier emails:")
    print(invalid_email.sum())


# ------------------------------------------------------------
# FINAL SUPPLIER VALIDATION
# ------------------------------------------------------------

print("\nFinal Suppliers missing values:")
print(suppliers.isnull().sum())

print("\nFinal Suppliers duplicates:")
print(suppliers.duplicated().sum())


# SAVE SUPPLIERS
suppliers.to_csv("suppliers_cleaned.csv", index=False)

print("\nSuppliers cleaned and saved successfully.")


# ============================================================
# 5. INVENTORY CLEANING
# ============================================================

print("\n========== INVENTORY CLEANING ==========")

print("\nShape:")
print(inventory.shape)

print("\nMissing values:")
print(inventory.isnull().sum())

print("\nDuplicate rows:")
print(inventory.duplicated().sum())

inventory = inventory.drop_duplicates().copy()


# ------------------------------------------------------------
# INVENTORY ID
# ------------------------------------------------------------

if "inventory_id" in inventory.columns:

    print("\nDuplicate inventory_id:")
    print(inventory["inventory_id"].duplicated().sum())


# ------------------------------------------------------------
# PRODUCT ID
# ------------------------------------------------------------

if "product_id" in inventory.columns:

    invalid_inventory_product_id = ~inventory["product_id"].astype(str).str.match(
        r"^PRD\d{4}$",
        na=False
    )

    print("\nInvalid product_id:")
    print(invalid_inventory_product_id.sum())


# ------------------------------------------------------------
# NUMERIC COLUMNS
# ------------------------------------------------------------

inventory_numeric_columns = [
    "stock_quantity",
    "reorder_level",
    "unit_cost"
]

for col in inventory_numeric_columns:

    if col in inventory.columns:

        inventory[col] = pd.to_numeric(
            inventory[col],
            errors="coerce"
        )

        print(f"\nNegative values in {col}:")
        print((inventory[col] < 0).sum())


# ------------------------------------------------------------
# STOCK STATUS
# ------------------------------------------------------------

if "stock_status" in inventory.columns:

    print("\nStock status:")
    print(inventory["stock_status"].value_counts(dropna=False))


# ------------------------------------------------------------
# OUT OF STOCK COUNT
# ------------------------------------------------------------

if "stock_status" in inventory.columns:

    print("\nOut of Stock products:")
    print(
        (inventory["stock_status"].astype(str).str.strip().str.lower()
         == "out of stock").sum()
    )


# ------------------------------------------------------------
# FINAL INVENTORY VALIDATION
# ------------------------------------------------------------

print("\nFinal Inventory missing values:")
print(inventory.isnull().sum())

print("\nFinal Inventory duplicates:")
print(inventory.duplicated().sum())


# SAVE INVENTORY
inventory.to_csv("inventory_cleaned.csv", index=False)

print("\nInventory cleaned and saved successfully.")


# ============================================================
# 6. CHECK ALL CLEANED FILES
# ============================================================

print("\n========== CLEANED FILES ==========")

cleaned_files = [
    "customers_cleaned.csv",
    "products_cleaned.csv",
    "payments_cleaned.csv",
    "order_items_cleaned.csv",
    "orders_cleaned.csv",
    "returns_cleaned.csv",
    "suppliers_cleaned.csv",
    "inventory_cleaned.csv"
]

for file in cleaned_files:

    if os.path.exists(file):

        df = pd.read_csv(file)

        print(
            f"{file:<30} "
            f"Rows: {df.shape[0]:<8} "
            f"Columns: {df.shape[1]}"
        )

    else:

        print(f"{file:<30} NOT FOUND")


print("\n========== CLEANING COMPLETE ==========")

Datasets loaded successfully.
Orders: (50000, 19)
Returns: (10000, 10)
Suppliers: (200, 14)
Inventory: (1000, 11)

========== ORDERS CLEANING ==========

Shape:
(50000, 19)

Missing values:
order_id                0
customer_id             0
order_date              0
order_time              0
status                  0
city                    0
state                   0
pincode                 0
total_amount            0
gst_amount              0
shipping_charge         0
discount_amount         0
final_amount            0
payment_method          0
shipping_partner        0
tracking_id             0
delivered_date      17501
is_cod                  0
channel                 0
dtype: int64

Duplicate rows:
0

Duplicate order_id:
0

Invalid order_id:
0

Date columns converted.

Negative values in gst_amount:
0

Negative values in discount_amount:
0

Negative values in total_amount:
0

Negative values in final_amount:
0

Delivered date before order date:
0

Orders above ₹5,00,000:
312

Final Orders missing values:
order_id                0
customer_id             0
order_date              0
order_time              0
status                  0
city                    0
state                   0
pincode                 0
total_amount            0
gst_amount              0
shipping_charge         0
discount_amount         0
final_amount            0
payment_method          0
shipping_partner        0
tracking_id             0
delivered_date      17501
is_cod                  0
channel                 0
dtype: int64

Final Orders duplicates:
0

Orders cleaned and saved successfully.

========== RETURNS CLEANING ==========

Shape:
(10000, 10)

Missing values:
return_id           0
order_id            0
customer_id         0
return_date         0
reason              0
return_amount       0
refund_status       0
refund_date         0
return_condition    0
remarks             0
dtype: int64

Duplicate rows:
0

Duplicate return_id:
0

Invalid return_id:
10000

Invalid return order_id:
0

Negative values in return_amount:
0

Final Returns missing values:
return_id           0
order_id            0
customer_id         0
return_date         0
reason              0
return_amount       0
refund_status       0
refund_date         0
return_condition    0
remarks             0
dtype: int64

Final Returns duplicates:
0

Returns cleaned and saved successfully.

========== SUPPLIERS CLEANING ==========

Shape:
(200, 14)

Missing values:
supplier_id           0
supplier_name         0
contact_person        0
email                 0
phone                 0
city                  0
state                 0
pincode               0
category              0
gstin                 0
payment_terms_days    0
rating                0
created_date          0
is_active             0
dtype: int64

Duplicate rows:
0

Duplicate supplier_id:
0

Invalid supplier_id:
0

Negative values in rating:
0

Invalid supplier emails:
0

Final Suppliers missing values:
supplier_id           0
supplier_name         0
contact_person        0
email                 0
phone                 0
city                  0
state                 0
pincode               0
category              0
gstin                 0
payment_terms_days    0
rating                0
created_date          0
is_active             0
dtype: int64

Final Suppliers duplicates:
0

Suppliers cleaned and saved successfully.

========== INVENTORY CLEANING ==========

Shape:
(1000, 11)

Missing values:
inventory_id             0
product_id               0
warehouse_location       0
quantity_available       0
quantity_reserved        0
reorder_level            0
reorder_quantity         0
last_restocked_date      0
unit_cost                0
total_inventory_value    0
status                   0
dtype: int64

Duplicate rows:
0

Duplicate inventory_id:
0

Invalid product_id:
0

Negative values in reorder_level:
0

Negative values in unit_cost:
0

Final Inventory missing values:
inventory_id             0
product_id               0
warehouse_location       0
quantity_available       0
quantity_reserved        0
reorder_level            0
reorder_quantity         0
last_restocked_date      0
unit_cost                0
total_inventory_value    0
status                   0
dtype: int64

Final Inventory duplicates:
0

Inventory cleaned and saved successfully.

========== CLEANED FILES ==========
customers_cleaned.csv          Rows: 10000    Columns: 17
products_cleaned.csv           Rows: 1000     Columns: 17
payments_cleaned.csv           Rows: 50000    Columns: 13
order_items_cleaned.csv        Rows: 100000   Columns: 11
orders_cleaned.csv             Rows: 50000    Columns: 19
returns_cleaned.csv            Rows: 10000    Columns: 10
suppliers_cleaned.csv          Rows: 200      Columns: 14
inventory_cleaned.csv          Rows: 1000     Columns: 11

========== CLEANING COMPLETE ==========

In [147]:
returns["return_id"].head(10)

0    RET00001
1    RET00002
2    RET00003
3    RET00004
4    RET00005
5    RET00006
6    RET00007
7    RET00008
8    RET00009
9    RET00010
Name: return_id, dtype: object

In [148]:
invalid_return_id = ~returns["return_id"].astype(str).str.match(
    r"^RET\d{5}$",
    na=False
)

invalid_return_id.sum()

np.int64(0)

In [149]:
print("Order Items → Orders:",
      (~order_items["order_id"].isin(orders["order_id"])).sum())

print("Order Items → Products:",
      (~order_items["product_id"].isin(products["product_id"])).sum())

print("Returns → Orders:",
      (~returns["order_id"].isin(orders["order_id"])).sum())

print("Inventory → Products:",
      (~inventory["product_id"].isin(products["product_id"])).sum())

Order Items → Orders: 0
Order Items → Products: 0
Returns → Orders: 0
Inventory → Products: 0

In [150]:
datasets = {
    "Customers": customers,
    "Products": products,
    "Payments": payments,
    "Order Items": order_items,
    "Orders": orders,
    "Returns": returns,
    "Suppliers": suppliers,
    "Inventory": inventory
}

for name, df in datasets.items():
    print("\n" + "="*50)
    print(name)
    print("="*50)
    print(df.dtypes)

==================================================
Customers
==================================================
customer_id                  object
first_name                   object
last_name                    object
email                        object
phone                         int64
city                         object
state                        object
pincode                       int64
gender                       object
age                           int64
segment                      object
registration_date    datetime64[ns]
last_login_date      datetime64[ns]
is_verified                   int64
is_active                     int64
total_orders                  int64
total_spent                 float64
dtype: object

==================================================
Products
==================================================
product_id               object
product_name             object
category                 object
subcategory              object
brand                    object
sku                      object
mrp                       int64
selling_price             int64
cost_price                int64
gst_rate                  int64
hsn_code                  int64
weight_grams              int64
supplier_id              object
rating                  float64
review_count              int64
is_active                 int64
launch_date      datetime64[ns]
dtype: object

==================================================
Payments
==================================================
payment_id                object
order_id                  object
customer_id               object
payment_date      datetime64[ns]
payment_time              object
payment_method            object
amount                   float64
status                    object
transaction_id            object
bank_name                 object
gateway                   object
refund_amount              int64
refund_date              float64
dtype: object

==================================================
Order Items
==================================================
item_id             object
order_id            object
product_id          object
product_name        object
category            object
quantity             int64
unit_price           int64
gst_rate             int64
gst_amount         float64
discount_amount    float64
total_price        float64
dtype: object

==================================================
Orders
==================================================
order_id                    object
customer_id                 object
order_date          datetime64[ns]
order_time                  object
status                      object
city                        object
state                       object
pincode                      int64
total_amount               float64
gst_amount                 float64
shipping_charge              int64
discount_amount            float64
final_amount               float64
payment_method              object
shipping_partner            object
tracking_id                 object
delivered_date      datetime64[ns]
is_cod                       int64
channel                     object
dtype: object

==================================================
Returns
==================================================
return_id                   object
order_id                    object
customer_id                 object
return_date         datetime64[ns]
reason                      object
return_amount              float64
refund_status               object
refund_date                 object
return_condition            object
remarks                     object
dtype: object

==================================================
Suppliers
==================================================
supplier_id            object
supplier_name          object
contact_person         object
email                  object
phone                   int64
city                   object
state                  object
pincode                 int64
category               object
gstin                  object
payment_terms_days      int64
rating                float64
created_date           object
is_active               int64
dtype: object

==================================================
Inventory
==================================================
inventory_id             object
product_id               object
warehouse_location       object
quantity_available        int64
quantity_reserved         int64
reorder_level             int64
reorder_quantity          int64
last_restocked_date      object
unit_cost                 int64
total_inventory_value     int64
status                   object
dtype: object

In [151]:
# Convert date columns to proper datetime format

payments["refund_date"] = pd.to_datetime(
    payments["refund_date"],
    errors="coerce"
)

suppliers["created_date"] = pd.to_datetime(
    suppliers["created_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

inventory["last_restocked_date"] = pd.to_datetime(
    inventory["last_restocked_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

returns["refund_date"] = pd.to_datetime(
    returns["refund_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [152]:
print("Payments refund_date:", payments["refund_date"].dtype)
print("Returns refund_date:", returns["refund_date"].dtype)
print("Suppliers created_date:", suppliers["created_date"].dtype)
print("Inventory last_restocked_date:", inventory["last_restocked_date"].dtype)

Payments refund_date: datetime64[ns]
Returns refund_date: datetime64[ns]
Suppliers created_date: datetime64[ns]
Inventory last_restocked_date: datetime64[ns]

In [153]:
customers["phone"] = customers["phone"].astype(str)
suppliers["phone"] = suppliers["phone"].astype(str)

In [154]:
inventory["total_inventory_value"] = inventory["total_inventory_value"].astype(float)

In [155]:
datasets = {
    "Customers": customers,
    "Products": products,
    "Payments": payments,
    "Order Items": order_items,
    "Orders": orders,
    "Returns": returns,
    "Suppliers": suppliers,
    "Inventory": inventory
}

for name, df in datasets.items():
    print("\n" + "="*50)
    print(name)
    print("="*50)
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Duplicate rows:", df.duplicated().sum())
    print("Total missing values:", df.isnull().sum().sum())
    print("\nData types:")
    print(df.dtypes)

==================================================
Customers
==================================================
Rows: 10000
Columns: 17
Duplicate rows: 0
Total missing values: 0

Data types:
customer_id                  object
first_name                   object
last_name                    object
email                        object
phone                        object
city                         object
state                        object
pincode                       int64
gender                       object
age                           int64
segment                      object
registration_date    datetime64[ns]
last_login_date      datetime64[ns]
is_verified                   int64
is_active                     int64
total_orders                  int64
total_spent                 float64
dtype: object

==================================================
Products
==================================================
Rows: 1000
Columns: 17
Duplicate rows: 0
Total missing values: 0

Data types:
product_id               object
product_name             object
category                 object
subcategory              object
brand                    object
sku                      object
mrp                       int64
selling_price             int64
cost_price                int64
gst_rate                  int64
hsn_code                  int64
weight_grams              int64
supplier_id              object
rating                  float64
review_count              int64
is_active                 int64
launch_date      datetime64[ns]
dtype: object

==================================================
Payments
==================================================
Rows: 50000
Columns: 13
Duplicate rows: 0
Total missing values: 50000

Data types:
payment_id                object
order_id                  object
customer_id               object
payment_date      datetime64[ns]
payment_time              object
payment_method            object
amount                   float64
status                    object
transaction_id            object
bank_name                 object
gateway                   object
refund_amount              int64
refund_date       datetime64[ns]
dtype: object

==================================================
Order Items
==================================================
Rows: 100000
Columns: 11
Duplicate rows: 0
Total missing values: 0

Data types:
item_id             object
order_id            object
product_id          object
product_name        object
category            object
quantity             int64
unit_price           int64
gst_rate             int64
gst_amount         float64
discount_amount    float64
total_price        float64
dtype: object

==================================================
Orders
==================================================
Rows: 50000
Columns: 19
Duplicate rows: 0
Total missing values: 17501

Data types:
order_id                    object
customer_id                 object
order_date          datetime64[ns]
order_time                  object
status                      object
city                        object
state                       object
pincode                      int64
total_amount               float64
gst_amount                 float64
shipping_charge              int64
discount_amount            float64
final_amount               float64
payment_method              object
shipping_partner            object
tracking_id                 object
delivered_date      datetime64[ns]
is_cod                       int64
channel                     object
dtype: object

==================================================
Returns
==================================================
Rows: 10000
Columns: 10
Duplicate rows: 0
Total missing values: 0

Data types:
return_id                   object
order_id                    object
customer_id                 object
return_date         datetime64[ns]
reason                      object
return_amount              float64
refund_status               object
refund_date         datetime64[ns]
return_condition            object
remarks                     object
dtype: object

==================================================
Suppliers
==================================================
Rows: 200
Columns: 14
Duplicate rows: 0
Total missing values: 0

Data types:
supplier_id                   object
supplier_name                 object
contact_person                object
email                         object
phone                         object
city                          object
state                         object
pincode                        int64
category                      object
gstin                         object
payment_terms_days             int64
rating                       float64
created_date          datetime64[ns]
is_active                      int64
dtype: object

==================================================
Inventory
==================================================
Rows: 1000
Columns: 11
Duplicate rows: 0
Total missing values: 0

Data types:
inventory_id                     object
product_id                       object
warehouse_location               object
quantity_available                int64
quantity_reserved                 int64
reorder_level                     int64
reorder_quantity                  int64
last_restocked_date      datetime64[ns]
unit_cost                         int64
total_inventory_value           float64
status                           object
dtype: object

In [156]:
customers.to_csv("customers_cleaned.csv", index=False)
payments.to_csv("payments_cleaned.csv", index=False)
returns.to_csv("returns_cleaned.csv", index=False)
suppliers.to_csv("suppliers_cleaned.csv", index=False)
inventory.to_csv("inventory_cleaned.csv", index=False)

In [157]:
import os

cleaned_files = [
    "customers_cleaned.csv",
    "products_cleaned.csv",
    "payments_cleaned.csv",
    "order_items_cleaned.csv",
    "orders_cleaned.csv",
    "returns_cleaned.csv",
    "suppliers_cleaned.csv",
    "inventory_cleaned.csv"
]

for file in cleaned_files:
    print(file, "→", os.path.exists(file))

customers_cleaned.csv → True
products_cleaned.csv → True
payments_cleaned.csv → True
order_items_cleaned.csv → True
orders_cleaned.csv → True
returns_cleaned.csv → True
suppliers_cleaned.csv → True
inventory_cleaned.csv → True